# frozen_string_literal: true

module Workshop
  # Renders the discovery index for a notes corpus: realm -> mission -> type, each note a
  # wikilink bullet plus an indented meta line. A pure function of the corpus — regenerated,
  # never edited by hand. Not a source of truth.
  class NotesIndex
    REALM_ORDER = Note::REALMS # professional, personal
    TYPE_ORDER = Note::TYPES   # decision, finding, gotcha, reference, question, lesson

    def initialize(corpus)
      @corpus = corpus
      @notes_dir = File.basename(corpus.dir)
    end

    def render
      out = ["# Engineering Notes Index", "Generated by `bin/note index`.", ""]

      by_realm.each do |realm, realm_notes|
        out << "## #{realm.capitalize}"
        by_mission(realm_notes).each do |mission, mission_notes|
          out << "### #{mission}"
          by_type(mission_notes).each do |type, type_notes|
            out << "#### #{type}"
            type_notes.each { |note| out.concat(entry(note)) }
          end
        end
        out << ""
      end

      "#{out.join("\n").strip}\n"
    end

    private

    attr_reader :corpus, :notes_dir

    def entry(note)
      ["- [[#{note.slug}]] — #{note.title}", "    #{meta(note)}"]
    end

    def meta(note)
      facets = ["#{notes_dir}/#{note.slug}.md", "`status: #{note.status}`"]
      facets << "`slice: #{note.slice}`" if note.slice
      facets << "`target: #{note.target}`" if note.target
      facets << "`tags: #{note.tags.join(', ')}`" unless note.tags.empty?
      facets.join(" · ")
    end

    def by_realm(notes = corpus.notes)
      grouped(notes, REALM_ORDER, &:realm)
    end

    def by_type(notes)
      grouped(notes, TYPE_ORDER, &:type)
    end

    # Missions have no canonical order, so sort alphabetically.
    def by_mission(notes)
      notes.group_by(&:mission).sort_by { |mission, _| mission }
    end

    # Group by an attribute, emit groups in the given order, skip empties.
    def grouped(notes, order, &attribute)
      buckets = notes.group_by(&attribute)
      order.filter_map { |key| [key, buckets[key]] if buckets.key?(key) }
    end
  end
end
